const crypto=require('crypto');
const COOKIE='ataraxia_admin';
const LOGIN_BUCKET=new Map();
function secret(){const s=process.env.ATARAXIA_SESSION_SECRET;if(!s||s.length<32)throw new Error('Missing session secret');return s}
function sign(payload){const body=Buffer.from(JSON.stringify(payload)).toString('base64url');const sig=crypto.createHmac('sha256',secret()).update(body).digest('base64url');return `${body}.${sig}`}
function verify(token){try{const [body,sig]=String(token||'').split('.');if(!body||!sig)return null;const expected=crypto.createHmac('sha256',secret()).update(body).digest('base64url');const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return null;const p=JSON.parse(Buffer.from(body,'base64url').toString());return p.exp>Date.now()/1000&&p.sub==='creator'?p:null}catch{return null}}
function originAllowed(req){const origin=String(req.headers.origin||'');if(!origin)return true;const allowed=(process.env.ATARAXIA_ALLOWED_ORIGIN||'').replace(/\/$/,'');return !!allowed&&origin===allowed}
function requireAdmin(req,res){if(!originAllowed(req))return res.status(403).json({error:'Origen no permitido'}),false;const raw=req.headers.cookie?.split(';').map(x=>x.trim()).find(x=>x.startsWith(COOKIE+'='));const p=verify(raw?.slice(COOKIE.length+1));if(!p){res.status(401).json({error:'No autorizado'});return false}return true}
function login(req,res){if(req.method!=='POST')return res.status(405).json({error:'Método no permitido'});if(!originAllowed(req))return res.status(403).json({error:'Origen no permitido'});if(!process.env.ATARAXIA_ADMIN_PASSWORD||process.env.ATARAXIA_ADMIN_PASSWORD.length<12||!process.env.ATARAXIA_SESSION_SECRET||process.env.ATARAXIA_SESSION_SECRET.length<32)return res.status(503).json({error:'Backend sin configuración segura'});const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0].trim(),now=Date.now(),prev=LOGIN_BUCKET.get(ip)||{start:now,count:0};if(now-prev.start<60000&&prev.count>=5)return res.status(429).json({error:'Demasiados intentos. Intenta nuevamente en un minuto.'});if(now-prev.start>=60000){LOGIN_BUCKET.set(ip,{start:now,count:1})}else{prev.count++;LOGIN_BUCKET.set(ip,prev)}const {password}=req.body||{};const a=Buffer.from(String(password||'')),b=Buffer.from(process.env.ATARAXIA_ADMIN_PASSWORD);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))return res.status(401).json({error:'Credenciales inválidas'});res.setHeader('Set-Cookie',`${COOKIE}=${sign({sub:'creator',exp:Math.floor(Date.now()/1000)+60*60*8})}; HttpOnly; Secure; SameSite=Strict; Path=/`);return res.json({ok:true})}
module.exports={requireAdmin,login};